apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: alie-api
  name: alie-api
spec:
  replicas: 6
  selector:
    matchLabels:
      io.kompose.service: alie-api
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: alie-api
    spec:
      containers:
        - image: harbor.alie.javeriana.edu.co/images/alie_api:latest
          name: alie-api
          env:
            - name: COCKROACHDB_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: db-user
            - name: COCKROACHDB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-pass
            - name: COCKROACHDB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: db-host
            - name: COCKROACHDB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: db-port
            - name: LMSTUDIO_HOST
              valueFrom:
                configMapKeyRef:
                  name: lms-config
                  key: host
            - name: LMSTUDIO_PORT
              valueFrom:
                configMapKeyRef:
                  name: lms-config
                  key: port
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: docs-db-secret
                  key: connectionString.standard
            - name: PINECONE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: external-apis-secret
                  key: pinecone-key
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: external-apis-secret
                  key: groq-key
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
      restartPolicy: Always
