# Usa una imagen base de Python
FROM python:3.10

# Establece el directorio de trabajo
WORKDIR /app

# Copia el archivo de dependencias al directorio de trabajo
COPY requirements.txt .

# Copia todos los archivos y carpetas del contexto de construcción al contenedor
COPY . .

# Instala las dependencias necesarias
RUN pip install -r requirements.txt

# Ejecutar el manejador de agentes
# CMD ["python", "ALIE_API.py"]

# Crea un script de inicio que ejecuta ambos comandos (inicializar Pinecone y luego servir la API del Manejador de agentes)
RUN echo '#!/bin/bash\npython Local_Agent/RAG/Pinecone_Init.py\npython ALIE_API.py' > /app/start.sh

# Da permisos de ejecución al script
RUN chmod +x /app/start.sh

# Ejecuta el script en lugar de CMD individual
CMD ["bash", "/app/start.sh"]

# Para construir la imagen individualmente, ejecuta el siguiente comando: docker build -t my-db-init-image .
# Para ejecutar el contenedor, ejecuta el siguiente comando: docker run my-db-init-image